kind: pipeline
type: docker
name: default

steps: 
  - name: golangci-lint
    image: golangci/golangci-lint:v1.31.0-alpine
    when:
      branch:
        - develop
        - main
      event:
        - cron
        - push
        - pull_request
        - tag
    commands:
      - golangci-lint run -E bodyclose -E gocyclo --timeout=10m

  - name: gosec
    image: securego/gosec:v2.8.1
    when:
      branch:
        - develop
        - main
      event:
        - cron
        - push
        - pull_request
        - tag
    commands:
      - gosec ./...

  - name: test
    image: golang:1.16.6
    when:
      branch:
        - develop
        - main
      event:
        - cron
        - push
        - pull_request
        - tag
    commands:
      - go test -race -cover ./...

  - name: build
    image: golang:1.16.6
    when:
      branch:
        - develop
        - main
      event:
        - cron
        - pull_request
        - tag
    commands:
      - export GO111MODULE=on
      - export CGO_ENABLED=1
      - export GOOS=linux
      - export GOARCH=amd64

      - flagBuildDate="-X 'github.com/ql31j45k3/SP_blog/configs.buildDate=`date -u '+%Y/%m/%d %H:%M:%S %p %Z'`'"

      - flagGitBranch="-X 'github.com/ql31j45k3/SP_blog/configs.gitBranch=${DRONE_COMMIT_BRANCH}'"
      - flagGitTag="-X 'github.com/ql31j45k3/SP_blog/configs.gitTag=${DRONE_TAG}'"
      - flagGitCommit="-X 'github.com/ql31j45k3/SP_blog/configs.gitCommit=${DRONE_COMMIT_SHA}'"

      - go build -race -ldflags "$flagBuildDate $flagGitBranch $flagGitTag $flagGitCommit" -o spBlogAPI ./cmd/blog_api/main.go

  - name: dev-deploy-api
    image: appleboy/drone-scp
    when:
      branch:
        - develop
      event:
        - cron
        - pull_request
    settings:
      host:
        from_secret: dev-deploy_api_host
      username:
        from_secret: dev-deploy_api_account
      password: 
        from_secret: dev-deploy_api_password
      port: 
        - 22
      command_timeout: 2m
      target: /srv/sp/api
      source: 
        - spBlogAPI

  - name: dev-restart-api
    image: appleboy/drone-ssh
    when:
      branch:
        - develop
      event:
        - cron
        - pull_request
    settings:
      host:
        from_secret: dev-deploy_api_host
      username:
        from_secret: dev-deploy_api_account
      password: 
        from_secret: dev-deploy_api_password
      port: 
        - 22
      command_timeout: 2m
      script:
        - systemctl stop sp-blog-api
        - systemctl start sp-blog-api
        - systemctl status sp-blog-api

  - name: dev-slack
    image: plugins/slack
    when:
      branch:
        - develop
      event:
        - cron
        - push
        - pull_request
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: dev_slack_webhook
      channel: dev-drone

  - name: prod-deploy-api
    image: appleboy/drone-scp
    when:
      branch:
        - master
      event:
        - tag
    settings:
      host:
        from_secret: prod-deploy_api_host
      username:
        from_secret: prod-deploy_api_account
      password:
        from_secret: prod-deploy_api_password
      port:
        - 22
      command_timeout: 2m
      target: /srv/sp/backup/${DRONE_TAG}/sp/api
      source:
        - spBlogAPI

  - name: prod-slack
    image: plugins/slack
    when:
      branch:
        - master
      event:
        - push
        - pull_request
        - tag
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: prod_slack_webhook
      channel: prod-drone

trigger:
  event:
    - cron
    - push
    - pull_request
    - tag